### ISSUE TITLE
Not able to retrieve bage off the dev branch when using this 

### ISSUE THREAD

**Issue by keshavneupane** [RubbaBoy/BYOBTest#1]
I tried using this however I was not able to retrieve the badge from the dev branch. I followed the readme and this is what I was looking at 
https://github.com/RubbaBoy/BYOB#basic-off-master-badge
Any suggestions? I can see the shields.json under the branch 'shields`

**Comment by RubbaBoy** [comment]
What does your link look like, pointing to the badge? (It must point to a public repo as well)
